### PR TITLE
chore(Flags): tidying the flags for the version/podtatoId

### PR DESCRIPTION
**Pull request by AlexsJones**
Updated pull request:

- Brings in main changes from #49
- Updates folder structure
   - Moves docker files into sub folder
   - Moves all html into the static folder ( updated dockerfile and code references)
   - Moved shell script into subfolder
- Improved existing deployment shell script
- Introduces a new GetAssembledPodtatoConfiguration method that reads from simple map construct and returns a new 
-  configuration object. ( Can be extended )

~~I am still trying to understand the relationship between the version and the podtato component ID, there seems to be none other than parsing the string for the ID.~~
 
~~~I hope this small tidying up though can help us to get somewhere a bit clearer where they both serve a purpose.~~

### CODE REVIEW

**Comment by AloisReitbauer** [comment]
Hey Alex,

this was a quick add. The idea is that different version can combine different components. Eg there can be version that used hands with ID 1 and and feet with ID 2.  As we work on splitting things into different services this will go away most likely.

**Comment by AloisReitbauer** [comment]
As eventually this - https://github.com/cncf/podtato-head/issues/8 - will be in place, I think it is best to read the ID configuration from a file or use a data structure to fill it at runtime based on the version.

**Comment by AlexsJones** [comment]
Updated pull request:

- Brings in main changes from https://github.com/cncf/podtato-head/pull/49
- Updates folder structure 
  - Moves docker files into sub folder
  - Moves all html into the static folder ( updated dockerfile and code references)
  - Moved shell script into subfolder 
- Improved existing deployment shell script 
- Introduces a new `GetAssembledPodtatoConfiguration` method that reads from simple map construct and returns a new configuration object. ( Can be extended )


**Tested**:
Build and run ✅
Docker build and push ✅
Helm chart install ✅
Port forward and test website ✅

**Review by thschue — APPROVED** [review]
lgtm

**Review by AloisReitbauer — APPROVED** [review]

**Comment by AloisReitbauer** [comment]
This is definitely much better. I think we should already allow different id for different body parts. This can be handled in a separate PR or in this one already.

**Comment by AlexsJones** [comment]
@AloisReitbauer Please see, this has been updated with a configuration of components e.g.
```
	"0.1.0": {
		BodyHats: BodyHats{Id: "01"},
		LeftArm:  LeftArm{Id: "01"},
		LeftLeg:  LeftLeg{Id: "01"},
		RightArm: RightArm{Id: "01"},
		RightLeg: RightLeg{Id: "01"},
	},
```

And we now selectively render
```
   <img src="./static/images/body.svg" style="position:absolute;margin-top:80px;margin-left:200px;">
      <img src="./static/images/hats/hat-{{.Components.BodyHats.Id}}.svg" style="position:absolute;margin-left:200px;margin-top:0px;">
      <img src="./static/images/left-arm/left-arm-{{.Components.LeftArm.Id}}.svg" style="position:absolute;top:100px;left:-50px;">
      <img src="./static/images/right-arm/right-arm-{{.Components.RightArm.Id}}.svg" style="position:absolute;top:100px;left:450px;">
      <img src="./static/images/left-leg/left-leg-{{.Components.LeftLeg.Id}}.svg" style="position:absolute;top:480px;left: -0px;" >
      <img src="./static/images/right-leg/right-leg-{{.Components.RightLeg.Id}}.svg" style="position:absolute;top:480px;left: 400px;">
```

LMK if you are good with these and I'll merge.

**Comment by AloisReitbauer** [comment]
lgtm

**Pull request merged**
