### PR TITLE
add kapp

### PR DESCRIPTION
**Pull request by yogeek**
Add Kapp deployment tool https://get-kapp.io/

### CODE REVIEW

**Comment by yogeek** [comment]
I just saw that I added `kustomize` ar the same time and refer to it in `kapp` readme : so if it is ok for you, i will add kustomize in the same PR ?

In addition, I also renamed in my fork all the `hello-server` reference to `podtato-head` (as mentionned in Slack with @AloisReitbauer) : i am not sure what is the best way to do ... another PR and then modify this one to reflect the name changes ? or all in this PR ?

**Comment by AloisReitbauer** [comment]
I am currently working on a bigger change to add additional services etc. Can we leave the hello server version here and then create a separate PR for the next version of the app. Otherwise, all examples need to be modified and we get some inconsistencies here.

**Comment by yogeek** [comment]
Yes of course.

I have another version in which I did the replacement from hello-server to podtato-head.
I could submit this PR first, in order to modify all the current examples with the new name.
And then we will be able to do other PRs to add new tools in a second times.

For this one, I will rename all to hello-server when I have the time.

**Comment by yogeek** [comment]
Hello @AloisReitbauer :)

just made the modifications to put back hello-server instead of pod-tato-head and added kustomize

**Comment by dirien** [comment]
Closed #19 in favor of this PR.

**Comment by AloisReitbauer** [comment]
Ok, so this one is ready to merge from your pov?

**Comment by yogeek** [comment]
@AloisReitbauer just added [this commit](https://github.com/cncf/podtato-head/pull/11/commits/57ba37bf705101d131c54d5212955d6b7668624b) to accept your change request

**Comment by AloisReitbauer** [comment]
Hey @yogeek can you have a look at the PR please. I would like to merge it.

**Comment by yogeek** [comment]
Hello @AloisReitbauer , I did the change you requested (see my last comment).
Did I miss something ?

**Comment by yogeek** [comment]
@AloisReitbauer I close this one in favor of #29, which is cleaner

**Pull request closed without merging**
